'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

'''
import math

lastlast = 1
last = 2
result = 2

while True:
	current = last + lastlast
	if current >= 4 * math.pow(10, 6):
		break
	if current % 2 == 0:
		result += current
	lastlast = last
	last = current

print(result)